name: bunyjs

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: bunyjs
      POSTGRES_PASSWORD: bunyjs
      POSTGRES_DB: bunyjs
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379

volumes:
  postgres-data:
